<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
        <AssemblyName>MetaTube</AssemblyName>
        <Authors>MetaTube</Authors>
        <Description>MetaTube Plugin for Jellyfin</Description>
        <Version>$([System.DateTime]::UtcNow.ToString(yyyy.Mdd.Hmm.0))</Version>
        <Copyright>Copyright © 2023 MetaTube</Copyright>
        <RepositoryType>Git</RepositoryType>
        <RepositoryUrl>https://github.com/jaconey/jellyfin-plugin-metatube.git</RepositoryUrl>
        <PackageProjectUrl>https://github.com/jaconey/jellyfin-plugin-metatube</PackageProjectUrl>
        <PackageLicenseUrl>https://github.com/jaconey/jellyfin-plugin-metatube/blob/main/LICENSE</PackageLicenseUrl>
        <PackageIcon>thumb.png</PackageIcon>
        <PackageId>MetaTube</PackageId>
        <Company>MetaTube</Company>
        <Product>MetaTube</Product>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Memory" Version="4.5.5"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Jellyfin.Controller" Version="10.11.1"/>
        <PackageReference Include="Jellyfin.Model" Version="10.11.1"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="Configuration\configPage.html"/>
        <EmbeddedResource Include="Configuration\configPage.html"/>
    </ItemGroup>

    <Target Name="Zip" AfterTargets="PostBuildEvent" Condition="'$(Configuration)'=='Release'">
        <ItemGroup>
            <FilesToDelete Include="$(BaseOutputPath)Jellyfin.MetaTube*.zip"/>
            <TempZipDirectory Include="$(OutputPath)output"/>
        </ItemGroup>
        <Delete Files="@(FilesToDelete)"/>
        <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll" DestinationFolder="@(TempZipDirectory)"/>
        <ZipDirectory SourceDirectory="@(TempZipDirectory)" DestinationFile="$(BaseOutputPath)Jellyfin.MetaTube@v$(Version).zip"/>
        <RemoveDir Directories="@(TempZipDirectory)"/>
    </Target>

</Project>
